# This is a basic workflow to help you get started with Actions

name: Docs-Deploy-to-Docs-Repository

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install pip-tools
          pip-compile setup.cfg
          pip-compile doc-requirements.in
          pip-sync requirements.txt doc-requirements.txt
      - name: python -m mkdocs build
        run: python -m mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.JIJZEPT_DOCS_DEPLOY_KEY }}
          external_repository: Jij-Inc/JijZept-References
          publish_branch: main
          publish_dir: ./site
          destination_dir: docs/jijbench
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          full_commit_message: ${{ github.event.head_commit.message }}
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
          enable_jekyll: false
