name: Test

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened, synchronize]



jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install poetry
        run: python3 -m pip install poetry
      - name: install packages
        run: python3 -m poetry install --no-interaction
      - name: run test
        run: poetry run pytest tests