# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package (jijzept-dev)

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  Python_Version: 3.9

jobs:
  Python-Build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v2
      
      - name: Set up Python  ${{env.Python_Version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.Python_Version}}
      - name: Create venv
        run: |
          python -m venv  --without-pip .venv
          source .venv/bin/activate
           
      - name: Install dependencies
        id: version
        run: |
          pip install --upgrade build setuptools wheel  pip 
          pip install setuptools-git-versioning 
         
      - name: Build Wheel
        run: |
          python ./setup.py bdist_wheel
    
      - name: Transfer Package  
        uses: actions/upload-artifact@v2
        with:
          name: package 
          path: ./dist
          retention-days: 1
          
  PyPI-Publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest   
    needs: Python-Build
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: package 
          path: ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://jij.jfrog.io/artifactory/api/pypi/Jij-Private
          user: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}
          packages_dir: ./dist
